#!/bin/bash

function failCommit() {
    tput setaf 1
    echo "----------------------------------------"
    echo "FATAL ERROR: $1"
    echo "----------------------------------------"
    tput sgr0
    exit 1
}

function testFail() {
    tput setaf 3
    echo "----------------------------------------"
    echo "$1"
    echo "----------------------------------------"
    tput sgr0
}

if git-rev-parse --verify HEAD >/dev/null 2>&1 ; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Remove all of the trailing whitespace in this commit
for FILE in `exec git diff-index --check --cached $against -- | sed '/^[+-]/d' | sed -E 's/:[0-9]+:.*//' | uniq` ; do
    sed -i '' -E 's/[[:space:]]*$//' "$FILE"
    git add $FILE
done

echo 'Running Lint...'
lintOutput=$(make lint 2>&1)
lintExitCode=$?
if [[ $lintExitCode -ne 0 ]]; then
    testFail "Lint errors detected"
    echo "$lintOutput"
    echo ''
    lintFailed=1
fi

if [[ $lintFailed ]]; then
    failCommit "Lint Errors"
fi

echo 'Running Tests...'
make test > /tmp/swig-test-output.txt 2>&1
testExitCode=$?
result=$(cat /tmp/swig-test-output.txt)
if [[ $testExitCode -ne 0 ]] || grep -qE '([1-9][0-9]*) failing' <<< "$result"; then
    testFail "Test failures detected"
    echo "$result"
    echo ''
    testsFailed=1
fi

if [[ $testsFailed || $lintFailed ]]; then
    failCommit "Unable To Commit"
fi
